第72章错字修正|标点修正
liuli-moe/to-the-stars pull request #113
Opened 2024-12-13 15:34 UTC by iolliotier

修正了一些错字和标点，同时一些句子也调整了下

2025-01-01 20:44 UTC, andylizi requested changes
感谢PR！抱歉这么久才来 review，文学翻译还是太费时费力了，好长时间才看完一半都不到，剩下的只能等下回继续（或者等别人来帮忙, whichever happen first :joy:）。若是等不耐烦了欢迎催我，不催的话我摸鱼的（逃

其实建议下回分成多次提交，每个PR小块一点，不必一个章节一个PR。不然每次我点开来想 review 的时候，一看到长长的滚动条就望而却步了，两百多个更改集中在一个PR里真的挺吓人的……

这个建议基本适用于一切情况，既包括写代码也包括写小说XD

![](https://github.com/user-attachments/assets/08fd9486-3caa-443c-ad24-86245bdafd5e)

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +然而，接触战争的到来使得虚拟化这个话题迅速升温。不仅仅是因为死亡这一伦理层面的灾难在四处蔓延，由于生物技术领域获得了巨大投入，再加上对外星生物技术的逆向工程，使得成功实现虚拟化的预计时间被缩短至一个世纪之内。〈此外，**事实上**某些人类已经具备有效的备份能力——即魔法少女，这使得一些相关的哲学问题变得无关紧要了，尽管此事对大多数人而言仍属机密。不过，无论出于何种理由，把备份能力局限于少数特权阶
此处「平等主义」和「平等主义原则」感觉都说得通，不过仔细想想我还是更喜欢「平等主义原则」一些？这种用法类似于 [人道主义原则 | 联合国难民署](https://emergency.unhcr.org/zh-hans/%E4%BF%9D%E6%8A%A4/%E4%BF%9D%E6%8A%A4%E5%8E%9F%E5%88%99/%E4%BA%BA%E9%81%93%E4%B8%BB%E4%B9%89%E5%8E%9F%E5%88%99) 之类的。不过说来说去两者区别也不大。

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +在/躯体-多样者的山间实验室中，似乎有无尽的材料可以收集，但良子最终还是说服自己去外面走走。她在此逗留的时间有限，了解外星人的社会至少与了解他们的科技同等重要。而且，比起一直盯着外星技术员的肩膀，四处走走或许能缓解一下烦躁的心情。
“至少与” 这个说法读起来感觉不太符合中文的表达习惯。

> 她在此逗留的时间有限，了解外星人社会的重要性不亚于他们的科技。

这样感觉如何？

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +外星人对良子的行动限制不多，只要求她别离实验室太远，以方便随时进行扫描。事实上，山间-漫步者似乎还挺乐意让她出去转转，并给她提供了不少建议，尽管她注意到这位英雄并没有提出要主动带路或陪同她。这又是一次考验吗？
> 没有提出要主动带路 -> 没有主动提出要带路

而且这里的“主动”感觉可以省去？说一个人没有主动做某事，有点隐含“最后这件事还是做了（只不过他没有主动提出而已）”的意味。百度汉语将这一词定义为：

> [形容词] 不待外力推动而行动。跟“被动”相对。

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +所幸，这边几乎没什么真正的危险。/躯体-多样者热衷于挑战他们身体能力的极限，他建议的下山路线虽然走起来并不轻松——但好在沿途有稳固的山石、结实的积雪，还有隐蔽的无线电信标不时指引方向。在克莱丽丝的帮助下，她很快就掌握了绳索的操作技巧，走得相当快。
「所幸的是」确实有些翻译腔，不过这种说法非常常见（能搜出成百上千的例句）；而「所幸，」二字后面跟上逗号，这读起来感觉怪怪的？而如果去掉逗号「所幸这边几乎没什么真正的危险。」也有点怪。

我提议要么保留「所幸的是」，要么把“几乎”去掉，毕竟原文说 "there was little..." 而不是 "there was little to none..."，没必要特意强调。

> 所幸这边没什么真正的危险。

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +**说真的，我在这里遇到的每个人都挺友好的**，良子对克莱丽丝念话道，**这个触手体看起来人还不错。我真希望能把这一切都展示给阿兹瑞尔看看**。
> 真希望能给阿兹瑞尔看看

进一步减少翻译腔

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +**等你去那些不那么友好的地方时，可别忘了这种感觉**，克莱丽丝想，**/躯体-多样者特意挑选了他们里面最友善的成员来接待你，所以这不能代表触手体的整体情况。以后的访问恐怕就不一定会这么愉快了**。
「他们中最友善的」感觉比「他们里面最友善的」更要自然一些？

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +随着太阳没入高耸的山峰之下，周围的环境也开始发生变化，裸露的岩石逐渐被饱经风霜的灌木和矮小的叶状植物取代。这些植物看起来有点古怪，就像类地球行星上的植物给人的那种陌生感一样，但她又说不出具体原因——或许只有亚纱美才会知道原因吧。
> it was the kind of thing Asami would probably have known

原文没有“**只有**她才知道（别人不会知道）”的含义。

> 这种事情亚纱美肯定知道吧。

强调“这种”，因为这属于亚纱美的兴趣爱好的领域，所以良子才会猜她知道。

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +这个问题提得很好，她已经与/非暴力-延伸者就此达成了默契。
呃，这个画风不太对劲哈 :joy: :joy:

![](https://github.com/user-attachments/assets/e334ef1f-3b1c-4348-b696-f2d58b07f3bf)

要不 “这是个好问题” ？

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +**||ν·我只能说我观察到的情况就是事实|ν+·但如果真相看起来前后矛盾，那就必须重新审视自己的假设了**
> I can only say what I have observed to be true

这句话意思更接近

> 我只能说我所见到的事实

“我观察到的情况就是事实” 这样就变成了 "what I have observed is the truth"，含义就变了。

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +良子一直专注于谈话，以至于没发现正从一栋建筑的拐角处探头偷看的两个年幼思裔，他们穿着鲜艳的红蓝两色衣服，眼睛又大又亮，看起来还挺可爱的——虽然这可能是因为她已经有点习惯看到章鱼了。
```suggestion
良子一直专注于谈话，以至于没发现一栋建筑拐角处的两个年幼思裔，探出头来偷看。他们穿着鲜艳的红蓝两色衣服，眼睛又大又亮，看上去真是惹人喜爱——虽然这可能是因为她已经有点习惯看到章鱼了。
```

原文 frankly endearing 的话，感觉 frankly 在此处恰好跟中文里 “真是” 的含义接近，因此能保留这层意思就太好了。而 “可爱” 更接近 cute，“惹人喜爱” 更符合 endearing 的含义。例如说百度汉语的例句：

> 小家伙虎头虎脑的，十分惹人喜爱。

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +**ৡ·你好，奇怪的外星人|∈·没人和我们说你会来这里拜访|∈·我们很惊讶，我们的监护人居然会让你这种潜在的危险分子靠我们这么近**
> We are surprised our caregivers would allow a potential danger so close
> 我们很惊讶，我们的监护人会允许潜在危险这么接近

“居然” 的语气太重了，原文是一个平和的陈述句。同样，“你这种危险分子” 语气太冲，明摆着是要来干架的，不太符合这里的场景。

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +**这比任何陆地章鱼都快**。克莱丽丝评论道。**很明显，这就是他们最初的交流方式。可惜现在他们好像不怎么用这个了**。
唉，apparently 翻译成 “显然” 是一个极其常见的翻译错误，各种场景（包括正式出版物）见到无数次了，可每次看到还是十分心塞……

https://www.zhihu.com/question/22463701/answer/40590038

> 看来这就是他们最初的交流方式。

2025-01-01 20:44 UTC, andylizi commented on books/04/072-第七十二章-芸芸众生.md
> +**这比任何陆地章鱼都快**。克莱丽丝评论道。**很明显，这就是他们最初的交流方式。可惜现在他们好像不怎么用这个了**。
今天暂时看到这里，剩下的之后再说……（咕咕咕

2025-01-05 14:22 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +然而，接触战争的到来使得虚拟化这个话题迅速升温。不仅仅是因为死亡这一伦理层面的灾难在四处蔓延，由于生物技术领域获得了巨大投入，再加上对外星生物技术的逆向工程，使得成功实现虚拟化的预计时间被缩短至一个世纪之内。〈此外，**事实上**某些人类已经具备有效的备份能力——即魔法少女，这使得一些相关的哲学问题变得无关紧要了，尽管此事对大多数人而言仍属机密。不过，无论出于何种理由，把备份能力局限于少数特权阶
这个原则一词是个人自己加上去的，但后来为了遵循原文又删了，不过如果读起来感觉**人道主义原则**一词在中文语句更通顺的话，个人可以重新再加上去

2025-01-06 13:19 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +在/躯体-多样者的山间实验室中，似乎有无尽的材料可以收集，但良子最终还是说服自己去外面走走。她在此逗留的时间有限，了解外星人的社会至少与了解他们的科技同等重要。而且，比起一直盯着外星技术员的肩膀，四处走走或许能缓解一下烦躁的心情。
可以，针对改善语句的建议都没什么问题

2025-01-06 13:21 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +外星人对良子的行动限制不多，只要求她别离实验室太远，以方便随时进行扫描。事实上，山间-漫步者似乎还挺乐意让她出去转转，并给她提供了不少建议，尽管她注意到这位英雄并没有提出要主动带路或陪同她。这又是一次考验吗？
山间-漫步者并没有给良子带路，所以主动一词可以删掉

2025-01-06 13:22 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +所幸，这边几乎没什么真正的危险。/躯体-多样者热衷于挑战他们身体能力的极限，他建议的下山路线虽然走起来并不轻松——但好在沿途有稳固的山石、结实的积雪，还有隐蔽的无线电信标不时指引方向。在克莱丽丝的帮助下，她很快就掌握了绳索的操作技巧，走得相当快。
`所幸这边没什么真正的危险。`
个人感觉这句比之前的两个提交都好，可以采纳

2025-01-06 13:23 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +**说真的，我在这里遇到的每个人都挺友好的**，良子对克莱丽丝念话道，**这个触手体看起来人还不错。我真希望能把这一切都展示给阿兹瑞尔看看**。
针对不合中文语境范句的更改个人没看出什么问题，可以改

2025-01-06 13:23 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +**等你去那些不那么友好的地方时，可别忘了这种感觉**，克莱丽丝想，**/躯体-多样者特意挑选了他们里面最友善的成员来接待你，所以这不能代表触手体的整体情况。以后的访问恐怕就不一定会这么愉快了**。
感觉确实自然一些，可以这样改

2025-01-06 13:24 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +随着太阳没入高耸的山峰之下，周围的环境也开始发生变化，裸露的岩石逐渐被饱经风霜的灌木和矮小的叶状植物取代。这些植物看起来有点古怪，就像类地球行星上的植物给人的那种陌生感一样，但她又说不出具体原因——或许只有亚纱美才会知道原因吧。
个人解读选择了只有一词，如果觉得不合原文，可以改为你建议的

2025-01-06 13:26 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +这个问题提得很好，她已经与/非暴力-延伸者就此达成了默契。
提高中文自然度的话，没问题

2025-01-06 13:27 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +**||ν·我只能说我观察到的情况就是事实|ν+·但如果真相看起来前后矛盾，那就必须重新审视自己的假设了**
重新看了一下，感觉确实是这样，就改为你的建议吧

2025-01-06 13:29 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +良子一直专注于谈话，以至于没发现正从一栋建筑的拐角处探头偷看的两个年幼思裔，他们穿着鲜艳的红蓝两色衣服，眼睛又大又亮，看起来还挺可爱的——虽然这可能是因为她已经有点习惯看到章鱼了。
这处更改出自个人的理解，如果觉得不符合原文的话，我可以改为`看起来真是惹人喜爱`

2025-01-06 13:31 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +**ৡ·你好，奇怪的外星人|∈·没人和我们说你会来这里拜访|∈·我们很惊讶，我们的监护人居然会让你这种潜在的危险分子靠我们这么近**
好像也是，原文没有危险份子一词，这种翻译出于个人理解，如果觉得影响了原文的含义的话，个人可以改为`我们的监护人会允许潜在危险这么接近我们`

2025-01-06 13:32 UTC, iolliotier commented on books/04/072-第七十二章-芸芸众生.md
> +**这比任何陆地章鱼都快**。克莱丽丝评论道。**很明显，这就是他们最初的交流方式。可惜现在他们好像不怎么用这个了**。
多谢查找问题，这个更改感觉在中文语境更通顺一些，可以这样改

2025-01-14 09:02 UTC, closed without merging