修改了第一章、第二章等的格式错误
liuli-moe/to-the-stars pull request #51
Opened 2024-06-06 02:48 UTC by bixudamajiang

2024-06-07 01:29 UTC, ArgusK17 commented
很多语法改变并不对吧。对于”XXX，“XX说，”XXX。“ 这里前半句引号里的句子用句号还是逗号结尾是取决于前后是否构成一个完整的句子，我看改动很多时候无脑改成了句号。建议再仔细考虑一下。

2024-06-07 01:46 UTC, bixudamajiang commented
我都是有仔细考虑过的，对于直接改为句号会不通顺的句子我会做处理发自我的麦芒-------- 原始邮件 --------发件人： Robert Clark ***@***.***>日期： 2024年6月7日周五 09:29收件人： liuli-moe/to-the-stars ***@***.***>抄送： bixudamajiang ***@***.***>, Author ***@***.***>主    题： Re: [liuli-moe/to-the-stars] 修改了第一章、第二章等的格式错误 (PR #51)
很多语法改变并不对吧。对于”XXX，“XX说，”XXX。“ 这里前半句引号里的句子用句号还是逗号结尾是取决于前后是否构成一个完整的句子，我看改动很多时候无脑改成了句号。建议再仔细考虑一下。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-07 03:21 UTC, bixudamajiang commented
对于一些疏忽的地方，我再改一改







                       
原始邮件
                       
                     

发件人："Robert Clark"< ***@***.*** &gt;;

发件时间：2024/6/7 9:29

收件人："liuli-moe/to-the-stars"< ***@***.*** &gt;;

抄送人："bixudamajiang"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [liuli-moe/to-the-stars] 修改了第一章、第二章等的格式错误 (PR #51)




 
很多语法改变并不对吧。对于”XXX，“XX说，”XXX。“ 这里前半句引号里的句子用句号还是逗号结尾是取决于前后是否构成一个完整的句子，我看改动很多时候无脑改成了句号。建议再仔细考虑一下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-06-07 03:52 UTC, bixudamajiang commented
修改好了，不过我似乎动到了第十章和第十一章，如果还有要改的地方我再看看

2024-06-26 23:51 UTC, andylizi requested changes

2024-06-26 23:51 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +“噢，对，是她，用了好些发卡的那个。”杏子说，丝毫没有意识到自己管别人叫作“发型夸张”有什么问题。
这句话就是麻美说的。

2024-06-26 23:51 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +“丘比，”她俯视着前方说：“抱歉打断一下，不过你感觉到了吗？”
根据国标 GB/T 15834―2011 [《标点符号用法》](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=22EA6D162E4110E752259661E1A0D0A8)

> #### B.1.5 冒号、逗号用于“说”“道”之类词语后的区别
> 位于引文之前的“说”“道”后用冒号。位于引文之后的“说训道”分两种情况：处于句末时，其后用句号；“说”“道”后还有其他成分时，其后用逗号。插在话语中间的“说”“道”类词语后只能用逗号表示停顿。
> * **示例 4**：“现在请皇上脱下衣服，”两个骗子说，“好让我们为您换上新衣。”

下同。

2024-06-26 23:51 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +“好吧，抱歉我刚才激动了。”她说，“我相信你，麻美。但是我听到的很多故事真的非常可怕。好好调查一下，然后我也去看看教会能帮到些什么。”
既然原文如此，作为译者，应当避免画蛇添足。这句话这样写无论是在中文还是在英文里，语法上都没问题。因此既然原作者决定要写成这样而不是那样，那我们翻译时不该越俎代庖。

下同。

2024-06-26 23:51 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +“啊——”良子抱歉地说，“——不好意思，是我要它更换下车地点的。那里有个著名的物理学家，我约了他见面。之后我会自己回去的。”
> “**A**——”，**B**，“——**C**”

就个人而言，破折号的这种用法，我从来没有见到过，查了一下也没查出什么。当然啦，这很可能只是我见识少而已。能否举一些现代文中这样写的例子呢？

下同。

2024-06-26 23:51 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +“其实……”她说，“……我对外语确实有点兴趣，不过……也没有**那么大的**兴趣。说实话，我根本不想呆在这里。”
类似的道理。既然原文没有选择使用省略号，为什么译文要选择使用省略号呢？

2024-06-26 23:51 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +尽管她们之前在河边讨论了一切，她的声音还是透出了遭到背叛的意味。
这样句子的意思就变了。就好比，“我吃过的一切水果” 跟 “我吃过了一切水果” 意思完全不一样。

2024-06-27 05:31 UTC, bixudamajiang commented on books/01/001-第一章-许愿.md
> +尽管她们之前在河边讨论了一切，她的声音还是透出了遭到背叛的意味。
其他的东西我都能理解，这一个我觉得中文语法上有些问题。
原文是:
```
"Ryouko!" Simona said, finally catching up to everything. "What are you doing?"
Despite everything they had said earlier, Simona's voice sounded betrayed.
```
“尽管她们之前在河边讨论的一切”这一句我不认为是一个完整的句子，“她们之前在河边讨论的一切”最后可以缩句成“一切”，而“尽管一切”不是一个完整的句子。原文也并不是这个意思，直译是“尽管她们之前讨论了那么多”。

2024-06-27 15:40 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +尽管她们之前在河边讨论了一切，她的声音还是透出了遭到背叛的意味。
我确实觉得 “尽管之前讨论的一切” 读起来怪怪的，但改成 “讨论了” 感觉也不太对劲……

这种说法的语料不太好找，相近的我只找到一个：

> Despite everything that had happened in the interim, they had remained good friends. 
> 不管在此间所发生的一切，他们还是好朋友。
> 《牛津高阶英汉双解词典》

仔细想了一想，把「的」改成「了」本身确实会通顺一些，但是如果改了的话就不应该用「一切」这个词了，因为「一切」失去了限定语，从「她们之前讨论过的所有话题」变成了「字面意义的无话不谈」。应该要换一个词……

……但我一时半会也想不出哪个词更好。

从含义上来分析，这句话的意思在文中是这样的：良子和西蒙娜之前说道她们如何如何对现状不满，如何如何觉得自己碌碌无为，如何如何想要“离开这里”。可现在契约的机会从天上掉了下来，良子真的能去追逐她的梦想了，西蒙娜反而就不高兴了，而是觉得受到了背叛。

因此这句话里 everything they had said earlier 是有明确的指向的，重心在于「她们之前讨论的内容」。如果改成「讨论了一切」的话，我感觉重心就变成「她们“讨论”的这个行为本身」了。

2024-06-27 16:01 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +“我——我不——”西蒙娜开口，在喘气的间隙里艰难地挤出了几个字。
其实之前这一处修改（把表示结巴的破折号改成省略号）我是赞同的，因为查了一下标点符号规范，

> **4.11 省略号**
> 4.11.3.4 标示说话时断断续续

而破折号就没有这个用法。这里的确是中文和英文的习惯用法不一致的例子。

2024-06-27 17:01 UTC, bixudamajiang commented on books/01/001-第一章-许愿.md
> +尽管她们之前在河边讨论了一切，她的声音还是透出了遭到背叛的意味。
想了半天，还是“尽管她们在河边讨论了那么多”来的合适

2024-06-27 17:02 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +尽管她们之前在河边讨论了一切，她的声音还是透出了遭到背叛的意味。
啊，这个不错！

2024-06-27 17:04 UTC, andylizi commented on books/01/001-第一章-许愿.md
> +尽管她们之前在河边讨论了一切，她的声音还是透出了遭到背叛的意味。
想了想，要不要强调一下“之前”？

> 尽管她们之前讨论了那么多，她的声音还是透出了遭到背叛的意味。

因为这样突出了西蒙娜前后态度的转变——她之前的讨论与她现在的态度。

2024-06-27 17:09 UTC, bixudamajiang commented on books/01/001-第一章-许愿.md
> +尽管她们之前在河边讨论了一切，她的声音还是透出了遭到背叛的意味。
可以，就这样吧

2024-06-27 17:14 UTC, andylizi approved these changes

2024-06-28 15:31 UTC, merged

2024-06-28 15:31 UTC, andylizi commented
谢谢！