攒了一点校对，断断续续，因为跳着看的
liuli-moe/to-the-stars pull request #68
Opened 2024-08-11 15:44 UTC by bixudamajiang

2024-08-11 15:50 UTC, andylizi commented
这个提交历史一团乱麻，请稍等让我理理清楚……

（你勾选了 "Allow edits from maintainers"，因此我这里可以直接编辑你的分支，不需要你操作）

2024-08-11 17:01 UTC, andylizi requested changes
太晚了，明天再继续看。

2024-08-11 17:01 UTC, andylizi commented on books/01/003-第三章-麻美观影记-上.md
> +在她右边的是战斗姿态的杏子，长矛摆着架势，身体半蹲，蓄势待发。作为传记作家们常常忘记的一个细节，导致杏子嘴里**没有**叼着任何食物，也没在身上揣着。
“作为……导致……” 感觉不太通顺

2024-08-11 17:01 UTC, andylizi commented on books/01/004-第四章-麻美观影记-下.md
> +“科技委员，” 麻美也一起念起了面会预约的名单，“国防委员、生产与分配委员、厚生委员、殖民委员、公安委员、人工智能委员、宣传委员。这还只算上了常务的。”
全文搜索了一下，书里出现的 AI 都是直接写作 AI 的，“人工智能”一词基本没有出现。

这里这些“委员”不应理解为职能部门。第八章开头解释过执政体的组织架构：

> 按照官方定义，执政体是一种由AI辅助的，人类可理解的抽象民主政体。其是作为众多统一战争前的理论家推崇的，由实用主义AI做主的技术统治论的代替而创建的。因此，执政体旨在产出在数学上尽可能接近技术统治论理论的结果，但其内在机制则完全不同。
> 
> 选民——不只是人类，还有所有知能体——的利益被分配给各委员负责，每位委员都被设计成或命令要尽可能地促进其负责主题的利益，这些利益既有具体的也有抽象的，从易于理解的“见泷原市粒子物理学家”到相对抽象的“科学与技术”都有。

因此这个“宣传”委员并不是字面意义上搞宣传的，而是反应公众意见的代表。“公安”同理。

2024-08-11 17:01 UTC, andylizi commented on books/01/006-第六章-军队.md
> +鄂温马克元帅刚刚传达了本次月中例会的议程，机械娘说。不出所料，本次的核心内容还是如何应对敌人在幼发拉底战区的侵略攻势。
「半月例会」 的说法是 #64 修改而来的。

2024-08-11 17:01 UTC, andylizi commented on books/01/007-第七章-南方组.md
> +**但是我可以往后发个 Tiro Finale。** 麻美解释说，**然后把它调成有后坐力的。**
```suggestion
**但是我可以往后发个 Tiro Finale，** 麻美解释说，**调成有后坐力的那种。**
```

2024-08-11 17:01 UTC, andylizi commented on books/01/008-第八章-政与教.md
> +只有在第二个目标，即将 AI 统一到人类社会中这方面，执政体可以说取得了彻底的成功。 AI 与人类现今已经近乎完全和谐地共存，这与过去许多人想象的反乌托邦情景相差甚远。
标点符号后面的西文无需空格。

2024-08-11 17:01 UTC, andylizi commented on books/01/008-第八章-政与教.md
> +当然，现在这些问题都已经解决得差不多了，而以 AI 为核心的政府体制也不再是问题。当今的人类委员是世界上强化程度最高的一群家伙。他们都进行了大范围的脑改造，加装了 “永久清醒模块”，随时连接着计算阵列，并且把一部分的神经元做了备份。每名委员都配有一个辅佐 AI 。这名 AI 在他或她相连的计算阵列里运行，既是在辅助人类处理一些事务，也是在监督着自己的人类部分尽心工作，不能腐败。委员们都会把自己的
标点符号前面的西文无需空格。

2024-08-11 17:01 UTC, andylizi commented on books/01/008-第八章-政与教.md
> +“大概是因为喝了十杯左右的咖啡？我不知道。那简直就像是童话剧本，对吧？比勒陀利亚惨案的第二天，整个实验室空空如也，只有我和拉普拉斯说着话，旁边放着一大壶咖啡。然后灵光一闪，我**看到**了。拉普拉斯都以为我神经了，突然滔滔不绝地自言自语起来。原来这一切就是那么简单！” ¹
这些角标先保持原样吧，我以后想改成用 `<sup></sup>` 的：

> “原来这一切就是那么简单！”  <sup>[1]</sup>

2024-08-11 17:01 UTC, andylizi commented on books/01/008-第八章-政与教.md
> +“M” 是 “MG” 的爱称，而 MG 则是 “魔法少女委员・辅佐 AI ”（Governance: Magical Girls—Advisory AI ）的英语字头。无论是辅佐职务还是正式委员，大多数的类似 AI 都会在日常会话中选择一个普通一点的名字，但眼前的少女 —— 大家都当她是少女 —— 似乎很喜欢 MG 这个奇特外号。
标点符号前后的西文不需要空格。

这样的例子太多了（看起来是批量查找替换的），因此之后我就不一一指出了。

2024-08-11 17:01 UTC, andylizi commented on books/99/012-译名对照表.md
> +| Takara				| 高良					|							|
这些表格大部分使用空格缩进而不是 tab，请统一成空格。反正汉字的话不管怎样排版都不可能完美对齐的。¯\\_(ツ)_/¯

后面有些“备注”也是 tab。

2024-08-12 06:01 UTC, bixudamajiang commented on books/01/004-第四章-麻美观影记-下.md
> +“科技委员，” 麻美也一起念起了面会预约的名单，“国防委员、生产与分配委员、厚生委员、殖民委员、公安委员、人工智能委员、宣传委员。这还只算上了常务的。”
我是按照琉璃的译名对照表更改的

2024-08-12 06:02 UTC, closed without merging